"""Secure adapter credential configuration helpers."""

import os
import shlex
import subprocess
from contextlib import suppress
from pathlib import Path

from ananke.plexus.core.paths import ensure_project_layout

CREDENTIAL_KEYS = [
    "ANANKE_REMOTE_LIVE_ENABLED",
    "ANANKE_REMOTE_LIVE_SERVICES",
    "ANANKE_JIRA_BASE_URL",
    "ANANKE_JIRA_EMAIL",
    "ANANKE_JIRA_TOKEN",
    "ANANKE_JIRA_BEARER_TOKEN",
    "ANANKE_JIRA_BEARER_TOKEN_CMD",
    "ANANKE_JIRA_TOKEN_CMD",
    "ANANKE_CONFLUENCE_BASE_URL",
    "ANANKE_CONFLUENCE_EMAIL",
    "ANANKE_CONFLUENCE_TOKEN",
    "ANANKE_CONFLUENCE_BEARER_TOKEN",
    "ANANKE_CONFLUENCE_BEARER_TOKEN_CMD",
    "ANANKE_CONFLUENCE_TOKEN_CMD",
    "ANANKE_BITBUCKET_BASE_URL",
    "ANANKE_BITBUCKET_WORKSPACE",
    "ANANKE_BITBUCKET_REPO_SLUG",
    "ANANKE_BITBUCKET_DEST_BRANCH",
    "ANANKE_BITBUCKET_USERNAME",
    "ANANKE_BITBUCKET_APP_PASSWORD",
    "ANANKE_BITBUCKET_BEARER_TOKEN",
    "ANANKE_BITBUCKET_BEARER_TOKEN_CMD",
    "ANANKE_BITBUCKET_APP_PASSWORD_CMD",
    "ANANKE_MCP_HTTP_TOKEN_CMD",
    "ANANKE_MCP_HTTP_TOKEN",
]

SECRET_KEYS = {
    "ANANKE_JIRA_TOKEN",
    "ANANKE_JIRA_BEARER_TOKEN",
    "ANANKE_CONFLUENCE_TOKEN",
    "ANANKE_CONFLUENCE_BEARER_TOKEN",
    "ANANKE_BITBUCKET_APP_PASSWORD",
    "ANANKE_BITBUCKET_BEARER_TOKEN",
    "ANANKE_MCP_HTTP_TOKEN",
}

DEFAULT_CREDENTIALS = {
    "ANANKE_REMOTE_LIVE_ENABLED": "false",
    "ANANKE_REMOTE_LIVE_SERVICES": "jira,confluence,bitbucket",
    "ANANKE_JIRA_BASE_URL": "https://example.atlassian.net",
    "ANANKE_JIRA_EMAIL": "",
    "ANANKE_JIRA_TOKEN": "",
    "ANANKE_JIRA_BEARER_TOKEN": "",
    "ANANKE_JIRA_BEARER_TOKEN_CMD": "",
    "ANANKE_JIRA_TOKEN_CMD": "",
    "ANANKE_CONFLUENCE_BASE_URL": "https://example.atlassian.net/wiki",
    "ANANKE_CONFLUENCE_EMAIL": "",
    "ANANKE_CONFLUENCE_TOKEN": "",
    "ANANKE_CONFLUENCE_BEARER_TOKEN": "",
    "ANANKE_CONFLUENCE_BEARER_TOKEN_CMD": "",
    "ANANKE_CONFLUENCE_TOKEN_CMD": "",
    "ANANKE_BITBUCKET_BASE_URL": "https://api.bitbucket.org",
    "ANANKE_BITBUCKET_WORKSPACE": "",
    "ANANKE_BITBUCKET_REPO_SLUG": "",
    "ANANKE_BITBUCKET_DEST_BRANCH": "main",
    "ANANKE_BITBUCKET_USERNAME": "",
    "ANANKE_BITBUCKET_APP_PASSWORD": "",
    "ANANKE_BITBUCKET_BEARER_TOKEN": "",
    "ANANKE_BITBUCKET_BEARER_TOKEN_CMD": "",
    "ANANKE_BITBUCKET_APP_PASSWORD_CMD": "",
    "ANANKE_MCP_HTTP_TOKEN_CMD": "",
    "ANANKE_MCP_HTTP_TOKEN": "",
}

LOCAL_CONFIG_TEMPLATE = """# Local-only overrides. This file is ignored by git.
# Secrets should be set in .ananke/secrets/adapters.env via `ananke configure auth`.

[jira]
base_url = { env = "ANANKE_JIRA_BASE_URL" }
email = { env = "ANANKE_JIRA_EMAIL" }
token = { env = "ANANKE_JIRA_TOKEN" }
bearer_token = { env = "ANANKE_JIRA_BEARER_TOKEN" }

[confluence]
base_url = { env = "ANANKE_CONFLUENCE_BASE_URL" }
email = { env = "ANANKE_CONFLUENCE_EMAIL" }
token = { env = "ANANKE_CONFLUENCE_TOKEN" }
bearer_token = { env = "ANANKE_CONFLUENCE_BEARER_TOKEN" }

[bitbucket]
base_url = { env = "ANANKE_BITBUCKET_BASE_URL" }
workspace = { env = "ANANKE_BITBUCKET_WORKSPACE" }
repo_slug = { env = "ANANKE_BITBUCKET_REPO_SLUG" }
destination_branch = { env = "ANANKE_BITBUCKET_DEST_BRANCH" }
username = { env = "ANANKE_BITBUCKET_USERNAME" }
app_password = { env = "ANANKE_BITBUCKET_APP_PASSWORD" }
bearer_token = { env = "ANANKE_BITBUCKET_BEARER_TOKEN" }

[lifecycle]
remote_live_enabled = { env = "ANANKE_REMOTE_LIVE_ENABLED" }
remote_live_services = { env = "ANANKE_REMOTE_LIVE_SERVICES" }

[mcp]
http_bearer_token = { env = "ANANKE_MCP_HTTP_TOKEN" }
"""


def _parse_env_like_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    parsed: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        parsed[key.strip()] = value.strip()
    return parsed


def _write_secure_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Ananke adapter credentials",
        "# Generated by `ananke configure auth`",
        "# Keep this file private; permissions are set to 600.",
        "",
    ]
    for key in CREDENTIAL_KEYS:
        lines.append(f"{key}={values.get(key, '')}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    with suppress(OSError):
        path.chmod(0o600)


def ensure_local_adapter_config(repository_root: Path) -> Path:
    layout = ensure_project_layout(repository_root)
    path = layout["base"] / "config.local.toml"
    if not path.exists():
        path.write_text(LOCAL_CONFIG_TEMPLATE, encoding="utf-8")
    return path


def ensure_credentials_store(repository_root: Path) -> Path:
    layout = ensure_project_layout(repository_root)
    secure_dir = layout["secrets"]
    secure_dir.mkdir(parents=True, exist_ok=True)
    with suppress(OSError):
        secure_dir.chmod(0o700)

    path = secure_dir / "adapters.env"
    merged = dict(DEFAULT_CREDENTIALS)
    merged.update(_parse_env_like_file(path))
    _write_secure_file(path, merged)
    return path


def read_credentials_store(repository_root: Path) -> dict[str, str]:
    path = ensure_credentials_store(repository_root)
    values = dict(DEFAULT_CREDENTIALS)
    values.update(_parse_env_like_file(path))
    return values


def auth_export_snippet(repository_root: Path, shell: str = "posix") -> tuple[Path, str]:
    path = ensure_credentials_store(repository_root)
    if shell in {"bash", "zsh", "sh", "posix"}:
        snippet = f'set -a\nsource "{path}"\nset +a'
    elif shell in {"fish"}:
        snippet = (
            f'for line in (cat "{path}")\n'
            '  if test (string trim "$line") = ""; or string match -qr "^#" -- "$line"\n'
            "    continue\n"
            "  end\n"
            '  set parts (string split -m1 "=" "$line")\n'
            "  set -gx $parts[1] $parts[2]\n"
            "end"
        )
    elif shell in {"powershell", "pwsh"}:
        snippet = (
            f'Get-Content "{path}" | ForEach-Object {{\n'
            "  if ($_ -match '^\\s*$' -or $_ -match '^#') { return }\n"
            "  $parts = $_.Split('=', 2)\n"
            "  [Environment]::SetEnvironmentVariable($parts[0], $parts[1], 'Process')\n"
            "}}"
        )
    elif shell in {"cmd", "cmd.exe"}:
        snippet = (
            f'for /f "usebackq tokens=1,* delims==" %A in ("{path}") do '
            '@if not "%A"=="" @if not "%A:~0,1%"=="#" set "%A=%B"'
        )
    elif shell in {"docker", "docker-env", "dotenv"}:
        snippet = f'--env-file "{path}"'
    else:
        snippet = f'set -a\nsource "{path}"\nset +a'
    return path, snippet


def resolve_secret_value(values: dict[str, str], key: str, command_key: str) -> str:
    direct = values.get(key, "").strip()
    if direct:
        return direct

    command = values.get(command_key, "").strip()
    if not command:
        return ""
    try:
        parts = shlex.split(command, posix=os.name != "nt")
    except ValueError:
        return ""
    if not parts:
        return ""

    try:
        result = subprocess.run(  # noqa: S603 - command is explicitly configured by the operator
            parts,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""

    if result.returncode != 0:
        return ""
    return result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""


def credential_validation_report(repository_root: Path) -> dict[str, object]:
    values = read_credentials_store(repository_root)
    result: dict[str, object] = {"ok": True, "services": {}}
    services: dict[str, object] = {}

    jira_missing: list[str] = []
    if not values.get("ANANKE_JIRA_BASE_URL", "").strip():
        jira_missing.append("ANANKE_JIRA_BASE_URL")
    jira_bearer = resolve_secret_value(
        values,
        "ANANKE_JIRA_BEARER_TOKEN",
        "ANANKE_JIRA_BEARER_TOKEN_CMD",
    )
    jira_token = resolve_secret_value(values, "ANANKE_JIRA_TOKEN", "ANANKE_JIRA_TOKEN_CMD")
    jira_email = values.get("ANANKE_JIRA_EMAIL", "").strip()
    if not jira_bearer and not (jira_email and jira_token):
        jira_missing.append(
            "ANANKE_JIRA_BEARER_TOKEN|ANANKE_JIRA_BEARER_TOKEN_CMD|"
            "(ANANKE_JIRA_EMAIL+ANANKE_JIRA_TOKEN|ANANKE_JIRA_TOKEN_CMD)"
        )
    services["jira"] = {"ready": len(jira_missing) == 0, "missing": jira_missing}

    confluence_missing: list[str] = []
    if not values.get("ANANKE_CONFLUENCE_BASE_URL", "").strip():
        confluence_missing.append("ANANKE_CONFLUENCE_BASE_URL")
    confluence_bearer = resolve_secret_value(
        values,
        "ANANKE_CONFLUENCE_BEARER_TOKEN",
        "ANANKE_CONFLUENCE_BEARER_TOKEN_CMD",
    )
    confluence_token = resolve_secret_value(
        values,
        "ANANKE_CONFLUENCE_TOKEN",
        "ANANKE_CONFLUENCE_TOKEN_CMD",
    )
    confluence_email = values.get("ANANKE_CONFLUENCE_EMAIL", "").strip()
    if not confluence_bearer and not (confluence_email and confluence_token):
        confluence_missing.append(
            "ANANKE_CONFLUENCE_BEARER_TOKEN|ANANKE_CONFLUENCE_BEARER_TOKEN_CMD|"
            "(ANANKE_CONFLUENCE_EMAIL+ANANKE_CONFLUENCE_TOKEN|ANANKE_CONFLUENCE_TOKEN_CMD)"
        )
    services["confluence"] = {
        "ready": len(confluence_missing) == 0,
        "missing": confluence_missing,
    }

    bitbucket_missing: list[str] = []
    for key in [
        "ANANKE_BITBUCKET_BASE_URL",
        "ANANKE_BITBUCKET_WORKSPACE",
        "ANANKE_BITBUCKET_REPO_SLUG",
    ]:
        if not values.get(key, "").strip():
            bitbucket_missing.append(key)
    bitbucket_bearer = resolve_secret_value(
        values,
        "ANANKE_BITBUCKET_BEARER_TOKEN",
        "ANANKE_BITBUCKET_BEARER_TOKEN_CMD",
    )
    bitbucket_password = resolve_secret_value(
        values,
        "ANANKE_BITBUCKET_APP_PASSWORD",
        "ANANKE_BITBUCKET_APP_PASSWORD_CMD",
    )
    bitbucket_username = values.get("ANANKE_BITBUCKET_USERNAME", "").strip()
    if not bitbucket_bearer and not (bitbucket_username and bitbucket_password):
        bitbucket_missing.append(
            "ANANKE_BITBUCKET_BEARER_TOKEN|ANANKE_BITBUCKET_BEARER_TOKEN_CMD|"
            "(ANANKE_BITBUCKET_USERNAME+ANANKE_BITBUCKET_APP_PASSWORD|ANANKE_BITBUCKET_APP_PASSWORD_CMD)"
        )
    services["bitbucket"] = {
        "ready": len(bitbucket_missing) == 0,
        "missing": bitbucket_missing,
    }

    for service in ["jira", "confluence", "bitbucket"]:
        state = services.get(service, {})
        if not isinstance(state, dict):
            result["ok"] = False
            continue
        if state.get("missing", []):
            services[service] = {
                "ready": bool(state.get("ready", False)),
                "missing": state.get("missing", []),
            }
            result["ok"] = False

    result["services"] = services
    return result


def update_credentials_store(
    repository_root: Path,
    updates: dict[str, str],
) -> tuple[Path, int, dict[str, str]]:
    path = ensure_credentials_store(repository_root)
    current = dict(DEFAULT_CREDENTIALS)
    current.update(_parse_env_like_file(path))

    changed = 0
    applied: dict[str, str] = {}
    for key, value in updates.items():
        if key not in DEFAULT_CREDENTIALS:
            continue
        if current.get(key) != value:
            changed += 1
        current[key] = value
        applied[key] = value

    _write_secure_file(path, current)
    return path, changed, applied
