"""Reproducible lockfiles (spec §50-§52).

``ananke.lock`` is deterministic TOML: same registry snapshot + same requirements produce
byte-identical output (no timestamps). It records exact versions, payload digests, the
registry snapshot, resolved dependency edges and source/provenance markers.
"""

from __future__ import annotations

import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from ananke.plexus.registry.errors import ManifestError
from ananke.plexus.registry.hashing import sha256_hex
from ananke.plexus.registry.models import LifecycleStatus, artifact_uri
from ananke.plexus.registry.resolver import ResolutionResult
from ananke.plexus.registry.tomlw import dumps

if TYPE_CHECKING:
    from ananke.plexus.registry.registry import Registry

LOCK_VERSION = 1
LOCK_NAME = "ananke.lock"


class LockRequirement(BaseModel):
    id: str
    req: str = "*"


class LockEntry(BaseModel):
    id: str
    version: str
    digest: str
    source: str = "local-registry"
    kind: str = ""
    dependencies: list[str] = Field(default_factory=list)
    requested_by: list[str] = Field(default_factory=list)
    dirty: bool = False
    path: str | None = None

    @property
    def sha256(self) -> str:
        return self.digest.split(":", 1)[-1]

    @property
    def ref(self) -> str:
        return f"{self.id}@{self.version}"


class Lockfile(BaseModel):
    version: int = LOCK_VERSION
    registry_snapshot: str = ""
    mode: str = "highest-compatible"
    requirements: list[LockRequirement] = Field(default_factory=list)
    entries: list[LockEntry] = Field(default_factory=list)

    def pins(self) -> dict[str, tuple[str, str]]:
        return {e.id: (e.version, e.sha256) for e in self.entries}

    def entry(self, uri: str) -> LockEntry | None:
        return next((e for e in self.entries if e.id == uri), None)


def build_lock(result: ResolutionResult, requirements: list[tuple[str, str]]) -> Lockfile:
    result.raise_if_failed()
    entries = [
        LockEntry(
            id=n.ref.uri,
            version=n.ref.version,
            digest=n.ref.digest,
            source=n.source,
            kind=n.kind.value,
            dependencies=sorted(d.ref for d in n.dependencies),
            requested_by=sorted(n.requested_by),
            dirty=n.dirty,
            path=n.override_path,
        )
        for n in result.nodes
    ]
    entries.sort(key=lambda e: e.id)
    return Lockfile(
        registry_snapshot=result.snapshot,
        mode=result.mode.value,
        requirements=sorted(
            (LockRequirement(id=uri, req=req) for uri, req in requirements), key=lambda r: r.id
        ),
        entries=entries,
    )


def dump_lock(lock: Lockfile) -> str:
    data: dict[str, Any] = {
        "version": lock.version,
        "registry_snapshot": lock.registry_snapshot,
        "mode": lock.mode,
        "requirement": [r.model_dump() for r in lock.requirements],
        "artifact": [
            {k: v for k, v in e.model_dump().items() if v not in (None, [], "", False)}
            for e in lock.entries
        ],
    }
    return dumps(data, header="# ananke.lock — generated by `ananke registry lock`. Do not edit.")


def parse_lock(text: str) -> Lockfile:
    try:
        raw = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ManifestError(f"invalid lockfile: {exc}") from exc
    if int(raw.get("version", 0)) != LOCK_VERSION:
        raise ManifestError(f"unsupported lockfile version {raw.get('version')!r}")
    return Lockfile(
        version=LOCK_VERSION,
        registry_snapshot=str(raw.get("registry_snapshot", "")),
        mode=str(raw.get("mode", "highest-compatible")),
        requirements=[LockRequirement(**r) for r in raw.get("requirement", [])],
        entries=[LockEntry(**e) for e in raw.get("artifact", [])],
    )


def load_lock(path: Path) -> Lockfile:
    return parse_lock(path.read_text(encoding="utf-8"))


def lock_hash(text: str) -> str:
    return "sha256:" + sha256_hex(text.encode())


def write_lock(
    registry: Registry | None, path: Path, lock: Lockfile, *, actor: str = "local"
) -> tuple[Path, str]:
    """Write ``path`` and, when a registry is given, record the lock (for GC reachability)."""
    text = dump_lock(lock)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    digest = lock_hash(text)
    if registry is not None:
        registry.store.record_lock(
            str(path),
            digest,
            lock.registry_snapshot,
            [e.sha256 for e in lock.entries],
            actor,
            registry.now(),
        )
        registry.emit(
            "lock.created",
            None,
            {"path": path.name, "lock_hash": digest, "artifacts": len(lock.entries)},
        )
    return path, digest


class LockCheck(BaseModel):
    id: str
    ok: bool
    detail: str = ""


def verify_lock(registry: Registry, lock: Lockfile) -> list[LockCheck]:
    """Every lock entry must exist, match its digest, have an intact blob, and not be quarantined."""
    checks: list[LockCheck] = []
    for e in lock.entries:
        if e.source == "path":
            checks.append(LockCheck(id=e.ref, ok=True, detail="path override (dirty)"))
            continue
        try:
            rec = registry.exact_version(e.ref)
        except Exception as exc:
            checks.append(LockCheck(id=e.ref, ok=False, detail=f"missing from registry: {exc}"))
            continue
        problems: list[str] = []
        if rec.digest_sha256 != e.sha256:
            problems.append("digest differs from registry")
        if rec.lifecycle is LifecycleStatus.QUARANTINED:
            problems.append("quarantined")
        try:
            registry.cas.get(e.sha256)
        except Exception as exc:
            problems.append(f"blob unavailable: {exc}")
        for dep in e.dependencies:
            if not any(x.ref == dep for x in lock.entries):
                problems.append(f"dependency {dep} missing from lock")
        checks.append(LockCheck(id=e.ref, ok=not problems, detail="; ".join(problems) or "ok"))
    return checks


def lock_uri(kind: str, namespace: str, name: str) -> str:
    return artifact_uri(kind, namespace, name)
