name: workflow-lint

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
